#personalQuestion
HowAreYou = ["how are you","whats up","what's up","what are you doing","hello","hey","hi"]
HowAreYouAnswer = ["I am fine, you","I am very good","I'm waiting for a command","hello how can I help you","thank you so much","I am for this"]
#SystemQuestion
SystemCommends = ["start terminal","terminal","open terminal","new terminal","show terminal"]
SystemCommendsReturn = ["showing terminal","terminal opening"]
Clock = ["hour","what","time","what time is it"]
#personalQuestion
YourName = ["what is your name","your name","how is","how is you"]
YourNameAnswer = ["hello I'm Mactans","How can I help you","I'm Mactans. I was created on January 25, 2020. That created me TAYYON"]
#System
Close = ["turn off the system","system is close","close" ,"close laptop" ,"off pc"]
CloseReturn =["System is Shutting Down"]
Search = ["search google","google search","search"]
OpenVideoProgram = ["Open video programs","video program","start video program"]
OpenVideoProgramReturn = ["Opening video programs", "okey ı am opening video programs"]
OpenGoogle = ["open google","google open","google browser open"]
MyFacebook = ["auto login my facebook","my facebook","open my facebook"]
MyFacebookReturn = ["facebook auto login started","entering your facebook","opening of facebook"]
Facebook = ["open facebook","facebook open","login facebook"]
FacebookReturn = ["opening facebook","login to facebook"]
Youtube = ["open youtube","login youtube","youtube open","youtube"]
YoutubeReturn = ["Opening youtube","login to Youtube"]
send_maill = ["email","mail","send mail","mail send"]
mail_return = ["Subject"]
alicilar = ["me","friendsl"]
mail_sender = ["who is the buyer","to whom should I send"]
Music = ["open music","music open","music"]
MusicReturn = ["opening your music list","music is opening"]
Word = ["Open word","word open","word","openload","Port open","dirt","North open","openwrt"]
FolderCreate = ["create folder", "folder", "create new folder"]
FolderReturn = ["folder is created","folder is created succesful"]
ClearScrean = ["clear screen","screen clear","clear","clear terminal","terminal clear"]
MyShcoolPage = ["open my school page","school page", "school","my school","ibuzem"]
MySchoolPageReturn = ["Opening your school page","okey  opening your school page"]
IP = ["my ip","ip","show my ip"]
IPReturn = ["Showing your ip address","your ip","ip is showed"]
ClosePC = ["shutdown my pc","close pc"]
ClosePCReturn = ["the computer will shut down in a few minutes"]
OpenMyGame = ["open my game","open my gate"]
MyGame = ["my game","second game"]